export const SELECT_MATCH = 'SELECT_MATCH'
export const SELECT_TOURNAMENT = 'SELECT_TOURNAMENT'
export const SELECT_SEASON = 'SELECT_SEASON'
export const SELECT_PLAYER = 'SELECT_PLAYER'

export const SET_HOVER_PLAYER = 'SET_HOVER_PLAYER'
